version: '3'
services:

  # Suite CRM database
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_suitecrm
      - MARIADB_DATABASE=bitnami_suitecrm
    volumes:
      - 'mariadb_data:/bitnami/mariadb'

  # Suite CRM app
  suitecrm:
    image: 'docker.io/bitnami/suitecrm:7-debian-10'
    ports:
      - '8080:8080'
      - '443:8443'
    environment:
      - SUITECRM_DATABASE_HOST=mariadb
      - SUITECRM_DATABASE_PORT_NUMBER=3306
      - SUITECRM_DATABASE_USER=bn_suitecrm
      - SUITECRM_DATABASE_NAME=bitnami_suitecrm
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'suitecrm_data:/bitnami/suitecrm'
    depends_on:
      - mariadb

  # Selenium chrome
  zalenium:
    image: dosel/zalenium
    command: zalenium start
    environment:
      - PULL_SELENIUM_IMAGE=true
    ports:
      - '4444:4444'
      - "5901:5900"
      - '7901:7900'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./videos:/tmp/videos
    restart: always

volumes:
  mariadb_data:
    driver: local
  suitecrm_data:
    driver: local
