name: Test Actions


on:
  #push:
   # branches:
     # - master
  workflow_dispatch:



jobs:
  test:
    env:
      RAILS_ENV: test
      NODE_ENV: test
      ALLOW_EMPTY_PASSWORD: yes
      MARIADB_USER: bn_suitecrm
      MARIADB_DATABASE: bitnami_suitecrm
      SUITECRM_DATABASE_HOST: mariadb
      SUITECRM_DATABASE_PORT_NUMBER: 3306
      SUITECRM_DATABASE_USER: bn_suitecrm
      SUITECRM_DATABASE_NAME: bitnami_suitecrm

      
    runs-on: ubuntu-latest # runner

    services:

            # Suite CRM database
      mariadb:
        env:
          ALLOW_EMPTY_PASSWORD: yes
          MARIADB_USER: bn_suitecrm
          MARIADB_DATABASE: bitnami_suitecrm
          
        image: 'docker.io/bitnami/mariadb:10.3-debian-10'
        volumes:
          - 'mariadb_data:/bitnami/mariadb'
        options: --name mariadb
        
      chrome:
        image: selenium/standalone-chrome-debug
        ports:
          - 4444:4444
          - 5900:5900
        volumes:
          - /dev/shm:/dev/shm
          
  # Suite CRM app
      suitecrm:
        env:
          ALLOW_EMPTY_PASSWORD: yes
          SUITECRM_DATABASE_HOST: mariadb
          SUITECRM_DATABASE_PORT_NUMBER: 3306
          SUITECRM_DATABASE_USER: bn_suitecrm
          SUITECRM_DATABASE_NAME: bitnami_suitecrm

        image: 'docker.io/bitnami/suitecrm:7-debian-10'
        ports:
          - '8080:8080'
          - '8443:8443'
        volumes:
          - 'suitecrm_data:/bitnami/suitecrm'
        options: --name suitecrm

    steps:

      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Cache Maven packages
        if: inputs.skip-maven-cache != true
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: sleep
        run: sleep 300
        
      - name: docker ps        
        run: docker ps -a
        
      - name: docker log crm      
        run: docker logs suitecrm
        
      - name: docker logs maria       
        run: docker logs mariadb

      - name: ping         
        run: curl http://127.0.0.1:8080
        
      - name: Build with Maven
        run: mvn -s ${{ github.workspace }}/.github/settings.xml  clean test -Ddriver.name="chrome-remote" -DpageUrl="localhost:8080" -Ddriver.remoteUrl="http://localhost:4444/wd/hub"
        
        
      - name: docker ps 2    
        if: always() 
        run: docker ps -a
        
      - name: docker log crm 2  
        if: always()
        run: docker logs suitecrm
        
      - name: docker logs maria 2    
        if: always()
        run: docker logs mariadb
        
      - name: Copy Report
        if: always()
        run: DIR1=$(ls ./logs | head -1); DIR2=$(ls ./logs/$DIR1 | head -1); cp ./logs/$DIR1/$DIR2/Report.html ./logs/index.html


      - name: Deploy to GitHub Pages
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: ./logs/index.html
